import { useCallback } from 'react';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

/**
 * FASE A2.7: Change Review Export Hook
 * Generates read-only PDF export of blueprint comparison review.
 * 
 * READ-ONLY: No DB writes, pure client-side export.
 */

export function useChangeReviewExport() {
  const exportReview = useCallback(async ({
    projectName,
    planName,
    currentVersion,
    compareVersion,
    changeCount,
    impactContext,
    suggestedActions,
    canvasElement,
    userName
  }) => {
    try {
      // Create hidden container for export
      const exportContainer = document.createElement('div');
      exportContainer.style.position = 'absolute';
      exportContainer.style.left = '-9999px';
      exportContainer.style.width = '210mm'; // A4 width
      exportContainer.style.backgroundColor = 'white';
      exportContainer.style.padding = '20mm';
      exportContainer.style.fontFamily = 'Arial, sans-serif';
      document.body.appendChild(exportContainer);

      // Build export HTML
      exportContainer.innerHTML = `
        <div style="color: #1e293b;">
          <!-- Header -->
          <div style="border-bottom: 3px solid #0f172a; padding-bottom: 16px; margin-bottom: 24px;">
            <h1 style="margin: 0; font-size: 24px; color: #0f172a;">Blueprint Change Review</h1>
            <div style="margin-top: 12px; font-size: 12px; color: #64748b;">
              <p style="margin: 4px 0;"><strong>Project:</strong> ${projectName || 'N/A'}</p>
              <p style="margin: 4px 0;"><strong>Plan:</strong> ${planName || 'N/A'}</p>
              <p style="margin: 4px 0;"><strong>Comparing:</strong> V${currentVersion} vs V${compareVersion}</p>
              <p style="margin: 4px 0;"><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
              <p style="margin: 4px 0;"><strong>By:</strong> ${userName || 'User'}</p>
            </div>
          </div>

          <!-- Change Summary -->
          <div style="background: #f1f5f9; border: 2px solid #cbd5e1; border-radius: 12px; padding: 16px; margin-bottom: 24px;">
            <h2 style="margin: 0 0 12px 0; font-size: 16px; color: #0f172a;">📊 Change Summary</h2>
            <div style="display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; font-size: 13px;">
              <div>
                <p style="margin: 4px 0; color: #64748b;">Total Changes:</p>
                <p style="margin: 4px 0; font-weight: bold; font-size: 18px; color: #f59e0b;">${changeCount}</p>
              </div>
              <div>
                <p style="margin: 4px 0; color: #64748b;">Impacted Tasks:</p>
                <p style="margin: 4px 0; font-weight: bold; font-size: 18px; color: #3b82f6;">${impactContext?.counts?.tasks || 0}</p>
              </div>
              <div>
                <p style="margin: 4px 0; color: #64748b;">Impacted Measurements:</p>
                <p style="margin: 4px 0; font-weight: bold; font-size: 18px; color: #10b981;">${impactContext?.counts?.measurements || 0}</p>
              </div>
              <div>
                <p style="margin: 4px 0; color: #64748b;">Impacted Photos:</p>
                <p style="margin: 4px 0; font-weight: bold; font-size: 18px; color: #8b5cf6;">${impactContext?.counts?.photos || 0}</p>
              </div>
            </div>
          </div>

          <!-- Suggested Actions -->
          ${suggestedActions && suggestedActions.length > 0 ? `
            <div style="margin-bottom: 24px;">
              <h2 style="margin: 0 0 12px 0; font-size: 16px; color: #0f172a;">💡 Suggested Actions</h2>
              <div style="space-y: 8px;">
                ${suggestedActions.map((action, idx) => {
                  const severityColors = {
                    high: '#ef4444',
                    medium: '#f59e0b',
                    low: '#3b82f6'
                  };
                  return `
                    <div style="border-left: 4px solid ${severityColors[action.severity]}; padding-left: 12px; margin-bottom: 12px; background: #f8fafc; padding: 12px; border-radius: 8px;">
                      <p style="margin: 0; font-weight: bold; font-size: 13px; color: #0f172a;">${idx + 1}. ${action.label}</p>
                      <p style="margin: 4px 0 0 0; font-size: 11px; color: #64748b;">${action.suggestedAction}</p>
                    </div>
                  `;
                }).join('')}
              </div>
            </div>
          ` : ''}

          <!-- Footer -->
          <div style="border-top: 2px solid #e2e8f0; padding-top: 16px; margin-top: 32px; text-align: center; color: #94a3b8; font-size: 11px;">
            <p style="margin: 0;">Generated by MCI Field</p>
            <p style="margin: 4px 0 0 0;">This is a read-only review document • ${new Date().toISOString()}</p>
          </div>
        </div>
      `;

      // Capture as canvas
      const canvas = await html2canvas(exportContainer, {
        scale: 2,
        backgroundColor: '#ffffff',
        logging: false
      });

      // Remove temp container
      document.body.removeChild(exportContainer);

      // Generate PDF
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      const imgData = canvas.toDataURL('image/png');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      const imgWidth = pdfWidth - 20; // margins
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      let heightLeft = imgHeight;
      let position = 10;

      // Add first page
      pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
      heightLeft -= pdfHeight;

      // Add additional pages if needed
      while (heightLeft > 0) {
        position = heightLeft - imgHeight + 10;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 10, position, imgWidth, imgHeight);
        heightLeft -= pdfHeight;
      }

      // Download
      const filename = `Change_Review_${planName?.replace(/[^a-z0-9]/gi, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
      pdf.save(filename);

      return { success: true };

    } catch (error) {
      console.error('Export error:', error);
      return { success: false, error: error.message };
    }
  }, []);

  return { exportReview };
}