import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

/**
 * PAYROLL PHASE 2 — Export Batch as CSV
 * Returns CSV content with summary row + allocation rows.
 */
Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { batch_id } = await req.json();

    if (!batch_id) {
      return Response.json({ error: 'batch_id required' }, { status: 400 });
    }

    // Fetch batch
    const batches = await base44.asServiceRole.entities.PayrollBatch.filter({ id: batch_id }, '', 1);
    if (!batches || batches.length === 0) {
      return Response.json({ error: 'Batch not found' }, { status: 404 });
    }
    const batch = batches[0];

    // Fetch allocations
    const allocations = await base44.asServiceRole.entities.PayrollAllocation.filter({ batch_id }, '', 1000);

    // Fetch employee names
    const profileIds = [...new Set((allocations || []).map(a => a.employee_profile_id))];
    const profiles = await Promise.all(
      profileIds.map(pid => base44.asServiceRole.entities.EmployeeProfile.filter({ id: pid }, '', 1).then(r => r?.[0]))
    );
    const userIds = [...new Set(profiles.filter(Boolean).map(p => p.user_id))];
    const users = await Promise.all(
      userIds.map(uid => base44.asServiceRole.entities.User.filter({ id: uid }, '', 1).then(r => r?.[0]))
    );
    const profileMap = Object.fromEntries(profiles.filter(Boolean).map(p => [p.id, p]));
    const userMap = Object.fromEntries(users.filter(Boolean).map(u => [u.id, u]));

    const generatedAt = new Date().toISOString();

    // Build CSV
    const lines = [];

    // Metadata header
    lines.push(`# Payroll Batch Export`);
    lines.push(`# Generated At: ${generatedAt}`);
    lines.push(`# Generated By: ${user.full_name || user.email}`);
    lines.push(`# Period: ${batch.period_start} to ${batch.period_end}`);
    lines.push(`# Status: ${batch.status}`);
    lines.push('');

    // Summary row
    lines.push(`SUMMARY`);
    lines.push(`Total Regular Hours,Total Overtime Hours,Total Commissions,Total Gross Pay`);
    lines.push(`${batch.total_regular_hours ?? 0},${batch.total_overtime_hours ?? 0},${batch.total_commissions ?? 0},${batch.total_gross ?? 0}`);
    lines.push('');

    // Allocation rows
    lines.push(`ALLOCATIONS`);
    lines.push(`Employee,Regular Hours,Overtime Hours,Hourly Rate,OT Multiplier,Regular Pay,Overtime Pay,Commission Total,Gross Pay`);

    for (const alloc of (allocations || [])) {
      const profile = profileMap[alloc.employee_profile_id];
      const empUser = profile ? userMap[profile.user_id] : null;
      const name = empUser?.full_name || profile?.first_name || 'Unknown';

      lines.push([
        `"${name}"`,
        alloc.regular_hours ?? 0,
        alloc.overtime_hours ?? 0,
        alloc.hourly_rate_snapshot ?? 0,
        alloc.overtime_multiplier_snapshot ?? 0,
        alloc.regular_pay ?? 0,
        alloc.overtime_pay ?? 0,
        alloc.commission_total ?? 0,
        alloc.gross_pay ?? 0
      ].join(','));
    }

    const csv = lines.join('\n');

    return new Response(csv, {
      headers: {
        'Content-Type': 'text/csv',
        'Content-Disposition': `attachment; filename="payroll_${batch.period_start}_${batch.period_end}.csv"`
      }
    });

  } catch (error) {
    console.error('Export CSV error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});