import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

/**
 * PAYROLL PHASE 3 — Export Batch as CSV (includes tax breakdown)
 */
Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { batch_id } = await req.json();
    if (!batch_id) return Response.json({ error: 'batch_id required' }, { status: 400 });

    // Fetch batch
    const batches = await base44.asServiceRole.entities.PayrollBatch.filter({ id: batch_id }, '', 1);
    if (!batches || batches.length === 0) return Response.json({ error: 'Batch not found' }, { status: 404 });
    const batch = batches[0];

    // Fetch allocations + tax breakdowns in parallel
    const [allocations, taxBreakdowns] = await Promise.all([
      base44.asServiceRole.entities.PayrollAllocation.filter({ batch_id }, '', 1000),
      base44.asServiceRole.entities.PayrollTaxBreakdown.filter({ batch_id }, '', 1000)
    ]);

    // Build tax lookup by allocation_id
    const taxMap = Object.fromEntries((taxBreakdowns || []).map(t => [t.allocation_id, t]));

    // Fetch employee names
    const profileIds = [...new Set((allocations || []).map(a => a.employee_profile_id))];
    const profiles = await Promise.all(
      profileIds.map(pid => base44.asServiceRole.entities.EmployeeProfile.filter({ id: pid }, '', 1).then(r => r?.[0]))
    );
    const userIds = [...new Set(profiles.filter(Boolean).map(p => p.user_id))];
    const users = await Promise.all(
      userIds.map(uid => base44.asServiceRole.entities.User.filter({ id: uid }, '', 1).then(r => r?.[0]))
    );
    const profileMap = Object.fromEntries(profiles.filter(Boolean).map(p => [p.id, p]));
    const userMap = Object.fromEntries(users.filter(Boolean).map(u => [u.id, u]));

    const generatedAt = new Date().toISOString();

    // Compute tax totals
    const totalNetPay = (taxBreakdowns || []).reduce((s, t) => s + (t.net_pay || 0), 0);
    const totalEmployerCost = (taxBreakdowns || []).reduce((s, t) => s + (t.employer_total_cost || 0), 0);

    const lines = [];

    // Metadata
    lines.push(`# Payroll Batch Export`);
    lines.push(`# Generated At: ${generatedAt}`);
    lines.push(`# Generated By: ${user.full_name || user.email}`);
    lines.push(`# Period: ${batch.period_start} to ${batch.period_end}`);
    lines.push(`# Status: ${batch.status}`);
    lines.push('');

    // Summary
    lines.push(`SUMMARY`);
    lines.push(`Total Regular Hours,Total Overtime Hours,Total Commissions,Total Gross Pay,Total Net Pay,Total Employer Cost`);
    lines.push(`${batch.total_regular_hours ?? 0},${batch.total_overtime_hours ?? 0},${batch.total_commissions ?? 0},${batch.total_gross ?? 0},${totalNetPay.toFixed(2)},${totalEmployerCost.toFixed(2)}`);
    lines.push('');

    // Allocations with tax breakdown
    lines.push(`ALLOCATIONS`);
    lines.push(`Employee,Tax Class,Regular Hours,Overtime Hours,Hourly Rate,OT Multiplier,Regular Pay,Overtime Pay,Commission,Gross Pay,SS Employee,Medicare Employee,SS Employer,Medicare Employer,FUTA,SUTA,Federal Withholding,State Withholding,Net Pay,Employer Total Cost`);

    for (const alloc of (allocations || [])) {
      const profile = profileMap[alloc.employee_profile_id];
      const empUser = profile ? userMap[profile.user_id] : null;
      const name = empUser?.full_name || profile?.first_name || 'Unknown';
      const tax = taxMap[alloc.id];

      lines.push([
        `"${name}"`,
        tax?.tax_classification || 'N/A',
        alloc.regular_hours ?? 0,
        alloc.overtime_hours ?? 0,
        alloc.hourly_rate_snapshot ?? 0,
        alloc.overtime_multiplier_snapshot ?? 0,
        alloc.regular_pay ?? 0,
        alloc.overtime_pay ?? 0,
        alloc.commission_total ?? 0,
        alloc.gross_pay ?? 0,
        tax?.social_security_employee ?? 'N/A',
        tax?.medicare_employee ?? 'N/A',
        tax?.social_security_employer ?? 'N/A',
        tax?.medicare_employer ?? 'N/A',
        tax?.futa ?? 'N/A',
        tax?.suta ?? 'N/A',
        tax?.federal_withholding ?? 'N/A',
        tax?.state_withholding ?? 'N/A',
        tax?.net_pay ?? 'N/A',
        tax?.employer_total_cost ?? 'N/A'
      ].join(','));
    }

    const csv = lines.join('\n');

    return new Response(csv, {
      headers: {
        'Content-Type': 'text/csv',
        'Content-Disposition': `attachment; filename="payroll_${batch.period_start}_${batch.period_end}.csv"`
      }
    });

  } catch (error) {
    console.error('Export CSV error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});