import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import { jsPDF } from 'npm:jspdf@2.5.1';

/**
 * PAYROLL PHASE 2 — Export Batch as PDF (A4 Landscape)
 */
Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { batch_id } = await req.json();

    if (!batch_id) {
      return Response.json({ error: 'batch_id required' }, { status: 400 });
    }

    // Fetch batch
    const batches = await base44.asServiceRole.entities.PayrollBatch.filter({ id: batch_id }, '', 1);
    if (!batches || batches.length === 0) {
      return Response.json({ error: 'Batch not found' }, { status: 404 });
    }
    const batch = batches[0];

    // Fetch allocations
    const allocations = await base44.asServiceRole.entities.PayrollAllocation.filter({ batch_id }, '', 1000);

    // Enrich employee names (batch fetch)
    const profileIds = [...new Set((allocations || []).map(a => a.employee_profile_id))];
    const profiles = await Promise.all(
      profileIds.map(pid => base44.asServiceRole.entities.EmployeeProfile.filter({ id: pid }, '', 1).then(r => r?.[0]))
    );
    const userIds = [...new Set(profiles.filter(Boolean).map(p => p.user_id))];
    const users = await Promise.all(
      userIds.map(uid => base44.asServiceRole.entities.User.filter({ id: uid }, '', 1).then(r => r?.[0]))
    );
    const profileMap = Object.fromEntries(profiles.filter(Boolean).map(p => [p.id, p]));
    const userMap = Object.fromEntries(users.filter(Boolean).map(u => [u.id, u]));

    const enriched = (allocations || []).map(alloc => {
      const profile = profileMap[alloc.employee_profile_id];
      const empUser = profile ? userMap[profile.user_id] : null;
      return { ...alloc, employee_name: empUser?.full_name || profile?.first_name || 'Unknown' };
    });

    // Generate PDF (A4 landscape)
    const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
    const W = 297; // A4 landscape width mm
    const generatedAt = new Date().toLocaleString();

    // Header
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('MCI Construction', 14, 18);

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Payroll Batch Report', 14, 26);

    // Period / Status
    doc.setFontSize(10);
    doc.text(`Period: ${batch.period_start}  →  ${batch.period_end}`, 14, 34);
    doc.text(`Status: ${batch.status.toUpperCase()}`, 14, 40);
    doc.text(`Generated: ${generatedAt}`, 14, 46);
    doc.text(`Generated By: ${user.full_name || user.email}`, 14, 52);

    // Horizontal rule
    doc.setLineWidth(0.5);
    doc.line(14, 56, W - 14, 56);

    // Summary totals
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Summary', 14, 63);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);

    const summaryY = 70;
    const colW = 60;
    const summaryItems = [
      ['Regular Hours', (batch.total_regular_hours ?? 0).toFixed(1)],
      ['Overtime Hours', (batch.total_overtime_hours ?? 0).toFixed(1)],
      ['Total Commissions', `$${(batch.total_commissions ?? 0).toFixed(2)}`],
      ['Total Gross Pay', `$${(batch.total_gross ?? 0).toFixed(2)}`]
    ];

    summaryItems.forEach(([label, value], i) => {
      const x = 14 + (i * colW);
      doc.setFont('helvetica', 'bold');
      doc.text(label, x, summaryY);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(14);
      doc.text(value, x, summaryY + 8);
      doc.setFontSize(10);
    });

    // Allocation table header
    let tableY = summaryY + 20;
    doc.setLineWidth(0.3);
    doc.line(14, tableY - 2, W - 14, tableY - 2);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);

    const cols = [
      { label: 'Employee', x: 14, w: 60 },
      { label: 'Reg Hours', x: 78, w: 25 },
      { label: 'OT Hours', x: 106, w: 25 },
      { label: 'Rate', x: 134, w: 25 },
      { label: 'OT Mult', x: 162, w: 20 },
      { label: 'Reg Pay', x: 185, w: 28 },
      { label: 'OT Pay', x: 216, w: 28 },
      { label: 'Commission', x: 247, w: 28 },
      { label: 'Gross Pay', x: 255 + 16, w: 28 }
    ];

    cols.forEach(col => doc.text(col.label, col.x, tableY));
    tableY += 5;
    doc.line(14, tableY, W - 14, tableY);
    tableY += 6;

    doc.setFont('helvetica', 'normal');

    for (const alloc of enriched) {
      if (tableY > 185) {
        doc.addPage();
        tableY = 20;
      }

      doc.text(alloc.employee_name.substring(0, 28), cols[0].x, tableY);
      doc.text(String((alloc.regular_hours ?? 0).toFixed(1)), cols[1].x, tableY);
      doc.text(String((alloc.overtime_hours ?? 0).toFixed(1)), cols[2].x, tableY);
      doc.text(`$${(alloc.hourly_rate_snapshot ?? 0).toFixed(2)}`, cols[3].x, tableY);
      doc.text(String(alloc.overtime_multiplier_snapshot ?? '1.5'), cols[4].x, tableY);
      doc.text(`$${(alloc.regular_pay ?? 0).toFixed(2)}`, cols[5].x, tableY);
      doc.text(`$${(alloc.overtime_pay ?? 0).toFixed(2)}`, cols[6].x, tableY);
      doc.text(`$${(alloc.commission_total ?? 0).toFixed(2)}`, cols[7].x, tableY);
      doc.setFont('helvetica', 'bold');
      doc.text(`$${(alloc.gross_pay ?? 0).toFixed(2)}`, cols[8].x, tableY);
      doc.setFont('helvetica', 'normal');

      tableY += 7;
    }

    const pdfBytes = doc.output('arraybuffer');

    return new Response(pdfBytes, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="payroll_${batch.period_start}_${batch.period_end}.pdf"`
      }
    });

  } catch (error) {
    console.error('Export PDF error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});