/**
 * Field PDF Generator
 * 
 * Generates production-grade PDFs with jsPDF
 */

import jsPDF from 'jspdf';

/**
 * Generate PDF from normalized dataset
 */
export async function generateFieldPDF(normalizedData, options = {}) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'letter'
  });
  
  let currentPage = 1;
  
  // Page 1: Cover + Metadata
  renderCoverPage(doc, normalizedData);
  
  // Page 2+: Dimensions by area
  const dimensionPages = renderDimensionPages(doc, normalizedData);
  currentPage += dimensionPages;
  
  // Benchmarks page (if any)
  if (normalizedData.benchmarks.length > 0) {
    doc.addPage();
    currentPage++;
    renderBenchmarksPage(doc, normalizedData, currentPage);
  }
  
  // Update metadata with page count
  normalizedData.metadata.page_count = doc.internal.pages.length - 1; // -1 for blank first page
  
  // Add page numbers and headers to all pages
  addHeadersAndFooters(doc, normalizedData);
  
  return {
    pdf: doc,
    blob: doc.output('blob'),
    data_url: doc.output('dataurlstring'),
    metadata: normalizedData.metadata
  };
}

/**
 * Render cover page
 */
function renderCoverPage(doc, data) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Company header
  doc.setFillColor(30, 58, 138); // MCI Blue
  doc.rect(0, 0, pageWidth, 60, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('MCI FIELD', pageWidth / 2, 35, { align: 'center' });
  
  // Document title
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.text('Field Dimension Report', pageWidth / 2, 100, { align: 'center' });
  
  // Project info box
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const boxY = 140;
  const lineHeight = 20;
  
  doc.text('Project:', 60, boxY);
  doc.setFont('helvetica', 'bold');
  doc.text(data.job.name, 140, boxY);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Address:', 60, boxY + lineHeight);
  doc.setFont('helvetica', 'bold');
  doc.text(data.job.address, 140, boxY + lineHeight);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Customer:', 60, boxY + lineHeight * 2);
  doc.setFont('helvetica', 'bold');
  doc.text(data.job.customer_name, 140, boxY + lineHeight * 2);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Area:', 60, boxY + lineHeight * 3);
  doc.setFont('helvetica', 'bold');
  doc.text(data.dimension_set.area, 140, boxY + lineHeight * 3);
  
  // Metadata
  doc.setFont('helvetica', 'normal');
  doc.text('Document ID:', 60, boxY + lineHeight * 5);
  doc.setFont('helvetica', 'bold');
  doc.text(data.metadata.document_id, 140, boxY + lineHeight * 5);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Revision:', 60, boxY + lineHeight * 6);
  doc.setFont('helvetica', 'bold');
  doc.text(`Rev ${data.metadata.revision_number}`, 140, boxY + lineHeight * 6);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Generated:', 60, boxY + lineHeight * 7);
  doc.setFont('helvetica', 'bold');
  doc.text(data.metadata.generated_at, 140, boxY + lineHeight * 7);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Generated By:', 60, boxY + lineHeight * 8);
  doc.setFont('helvetica', 'bold');
  doc.text(data.metadata.generated_by, 140, boxY + lineHeight * 8);
  
  // Status badge
  const statusY = boxY + lineHeight * 10;
  doc.setFillColor(34, 197, 94); // Green
  doc.roundedRect(60, statusY - 10, 100, 20, 3, 3, 'F');
  doc.setTextColor(255, 255, 255);
  doc.text(data.dimension_set.workflow_state.toUpperCase(), 110, statusY + 2, { align: 'center' });
  
  // Offline indicator
  if (data.metadata.offline_generated) {
    doc.setTextColor(255, 140, 0);
    doc.setFontSize(8);
    doc.text('Generated Offline', pageWidth / 2, pageHeight - 20, { align: 'center' });
  }
}

/**
 * Render dimension pages
 */
function renderDimensionPages(doc, data) {
  const { groupDimensionsForProduction, calculateWallSequences, formatDimensionRow } = require('./FieldPDFLayoutEngine');
  
  let pagesAdded = 0;
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Group dimensions by area
  const areaGroups = groupDimensionsForProduction(data.dimensions);
  
  areaGroups.forEach(areaGroup => {
    doc.addPage();
    pagesAdded++;
    
    let y = 100; // Start below header
    
    // Area title
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`Area: ${areaGroup.area_name}`, 40, y);
    y += 25;
    
    // Wall-to-Wall Dimensions
    if (areaGroup.wall_dimensions.length > 0) {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Wall-to-Wall Dimensions', 40, y);
      y += 20;
      
      // Table header
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text('#', 40, y);
      doc.text('Type', 60, y);
      doc.text('Imperial', 120, y);
      doc.text('Metric', 200, y);
      doc.text('Tolerance', 270, y);
      doc.text('Benchmark', 340, y);
      doc.text('Notes', 420, y);
      
      y += 5;
      doc.setLineWidth(0.5);
      doc.line(40, y, pageWidth - 40, y);
      y += 12;
      
      // Wall sequences
      const sequences = calculateWallSequences(areaGroup.wall_dimensions);
      
      Object.entries(sequences).forEach(([type, dims]) => {
        if (dims.length === 0) return;
        
        dims.forEach((dim, idx) => {
          if (y > 700) {
            doc.addPage();
            pagesAdded++;
            y = 100;
          }
          
          const row = formatDimensionRow(dim, idx);
          
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(8);
          doc.text(row.index.toString(), 40, y);
          doc.text(row.type, 60, y);
          doc.setFont('helvetica', 'bold');
          doc.text(row.imperial, 120, y);
          doc.setFont('helvetica', 'normal');
          doc.text(row.metric, 200, y);
          doc.text(row.tolerance, 270, y);
          doc.text(row.benchmark, 340, y);
          doc.setFontSize(7);
          doc.text(row.notes, 420, y);
          
          y += 15;
        });
        
        y += 5; // Space between types
      });
      
      y += 10;
    }
    
    // Vertical Dimensions
    if (areaGroup.vertical_dimensions.length > 0) {
      if (y > 600) {
        doc.addPage();
        pagesAdded++;
        y = 100;
      }
      
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Vertical Dimensions', 40, y);
      y += 20;
      
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text('#', 40, y);
      doc.text('Type', 60, y);
      doc.text('Imperial', 120, y);
      doc.text('Metric', 200, y);
      doc.text('Benchmark', 270, y);
      
      y += 5;
      doc.line(40, y, pageWidth - 40, y);
      y += 12;
      
      areaGroup.vertical_dimensions.forEach((dim, idx) => {
        if (y > 700) {
          doc.addPage();
          pagesAdded++;
          y = 100;
        }
        
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.text((idx + 1).toString(), 40, y);
        doc.text(dim.measurement_type, 60, y);
        doc.setFont('helvetica', 'bold');
        doc.text(dim.display_value_imperial, 120, y);
        doc.setFont('helvetica', 'normal');
        doc.text(dim.display_value_metric, 200, y);
        doc.text(dim.benchmark_label || '-', 270, y);
        
        y += 15;
      });
    }
  });
  
  return pagesAdded;
}

/**
 * Render benchmarks page
 */
function renderBenchmarksPage(doc, data, pageNum) {
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 100;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Benchmark Reference Points', 40, y);
  y += 25;
  
  // Note
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(100, 100, 100);
  doc.text('All vertical measurements reference these benchmarks', 40, y);
  doc.setTextColor(0, 0, 0);
  y += 20;
  
  // Table header
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Label', 40, y);
  doc.text('Type', 120, y);
  doc.text('Elevation', 200, y);
  doc.text('Area', 280, y);
  doc.text('Established By', 380, y);
  doc.text('Date', 480, y);
  
  y += 5;
  doc.setLineWidth(0.5);
  doc.line(40, y, pageWidth - 40, y);
  y += 12;
  
  // Benchmark rows
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  
  data.benchmarks.forEach((bm, idx) => {
    if (y > 700) {
      doc.addPage();
      y = 100;
    }
    
    // Highlight row background
    if (idx % 2 === 0) {
      doc.setFillColor(248, 250, 252);
      doc.rect(35, y - 8, pageWidth - 70, 15, 'F');
    }
    
    doc.setFont('helvetica', 'bold');
    doc.text(bm.label, 40, y);
    doc.setFont('helvetica', 'normal');
    doc.text(bm.type, 120, y);
    doc.setFont('helvetica', 'bold');
    doc.text(`${bm.elevation} ${bm.elevation_unit}`, 200, y);
    doc.setFont('helvetica', 'normal');
    doc.text(bm.area, 280, y);
    doc.text(bm.established_by, 380, y);
    doc.text(bm.established_date, 480, y);
    
    y += 18;
  });
}

/**
 * Add headers and footers to all pages
 */
function addHeadersAndFooters(doc, data) {
  const pageCount = doc.internal.pages.length - 1;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  for (let i = 2; i <= pageCount; i++) { // Skip cover page
    doc.setPage(i);
    
    // Header
    doc.setFillColor(240, 240, 240);
    doc.rect(0, 0, pageWidth, 50, 'F');
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('MCI FIELD', 40, 30);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(data.metadata.document_id, pageWidth - 40, 30, { align: 'right' });
    
    // Footer
    doc.setFontSize(8);
    doc.text(`Page ${i - 1} of ${pageCount - 1}`, pageWidth / 2, pageHeight - 20, { align: 'center' });
    doc.text(`Rev ${data.metadata.revision_number}`, pageWidth - 40, pageHeight - 20, { align: 'right' });
  }
}