/**
 * Field PDF Generator
 * 
 * Generates production-grade PDFs with jsPDF
 */

import jsPDF from 'jspdf';

/**
 * Generate PDF from normalized dataset
 */
export async function generateFieldPDF(normalizedData, options = {}) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'letter'
  });
  
  let currentPage = 1;
  
  // Page 1: Cover + Metadata
  renderCoverPage(doc, normalizedData);
  
  // Page 2: Legend & Guide
  doc.addPage();
  currentPage++;
  renderLegendPage(doc, normalizedData, currentPage);
  
  // Page 3+: Dimensions by area
  const dimensionPages = renderDimensionPages(doc, normalizedData);
  currentPage += dimensionPages;
  
  // Benchmarks page (if any)
  if (normalizedData.benchmarks.length > 0) {
    doc.addPage();
    currentPage++;
    renderBenchmarksPage(doc, normalizedData, currentPage);
  }
  
  // Update metadata with page count
  normalizedData.metadata.page_count = doc.internal.pages.length - 1; // -1 for blank first page
  
  // Add page numbers and headers to all pages
  addHeadersAndFooters(doc, normalizedData);
  
  return {
    pdf: doc,
    blob: doc.output('blob'),
    data_url: doc.output('dataurlstring'),
    metadata: normalizedData.metadata
  };
}

/**
 * Render cover page
 */
function renderCoverPage(doc, data) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Company header
  doc.setFillColor(30, 58, 138); // MCI Blue
  doc.rect(0, 0, pageWidth, 60, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('MCI FIELD', pageWidth / 2, 35, { align: 'center' });
  
  // Document title
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.text('Field Dimension Report', pageWidth / 2, 100, { align: 'center' });
  
  // Project info box
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const boxY = 140;
  const lineHeight = 20;
  
  doc.text('Project:', 60, boxY);
  doc.setFont('helvetica', 'bold');
  doc.text(data.job.name, 140, boxY);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Address:', 60, boxY + lineHeight);
  doc.setFont('helvetica', 'bold');
  doc.text(data.job.address, 140, boxY + lineHeight);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Customer:', 60, boxY + lineHeight * 2);
  doc.setFont('helvetica', 'bold');
  doc.text(data.job.customer_name, 140, boxY + lineHeight * 2);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Area:', 60, boxY + lineHeight * 3);
  doc.setFont('helvetica', 'bold');
  doc.text(data.dimension_set.area, 140, boxY + lineHeight * 3);
  
  // Metadata
  doc.setFont('helvetica', 'normal');
  doc.text('Document ID:', 60, boxY + lineHeight * 5);
  doc.setFont('helvetica', 'bold');
  doc.text(data.metadata.document_id, 140, boxY + lineHeight * 5);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Revision:', 60, boxY + lineHeight * 6);
  doc.setFont('helvetica', 'bold');
  doc.text(`Rev ${data.metadata.revision_number}`, 140, boxY + lineHeight * 6);
  
  // Change summary (if not initial revision)
  if (data.metadata.change_summary && data.metadata.change_summary.summary_text !== 'Initial revision') {
    doc.setFont('helvetica', 'normal');
    doc.text('Changes:', 60, boxY + lineHeight * 7);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    const changeSummaryLines = doc.splitTextToSize(data.metadata.change_summary.summary_text, pageWidth - 160);
    changeSummaryLines.forEach((line, idx) => {
      doc.text(line, 140, boxY + lineHeight * 7 + (idx * 10));
    });
    doc.setFontSize(10);
  }
  
  doc.setFont('helvetica', 'normal');
  doc.text('Generated:', 60, boxY + lineHeight * 9);
  doc.setFont('helvetica', 'bold');
  doc.text(data.metadata.generated_at, 140, boxY + lineHeight * 9);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Generated By:', 60, boxY + lineHeight * 10);
  doc.setFont('helvetica', 'bold');
  doc.text(data.metadata.generated_by, 140, boxY + lineHeight * 10);
  
  // Status badge
  const statusY = boxY + lineHeight * 12;
  doc.setFillColor(34, 197, 94); // Green
  doc.roundedRect(60, statusY - 10, 100, 20, 3, 3, 'F');
  doc.setTextColor(255, 255, 255);
  doc.text(data.dimension_set.workflow_state.toUpperCase(), 110, statusY + 2, { align: 'center' });
  
  // Revision badge (if not initial)
  if (data.metadata.revision_number > 1) {
    doc.setFillColor(59, 130, 246); // Blue
    doc.roundedRect(180, statusY - 10, 80, 20, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.text(`REV ${data.metadata.revision_number}`, 220, statusY + 2, { align: 'center' });
  }
  
  // Offline indicator with pending sync status
  if (data.metadata.offline_generated) {
    const statusY = pageHeight - 30;
    
    doc.setFillColor(255, 237, 213); // Orange background
    doc.roundedRect(pageWidth / 2 - 80, statusY - 12, 160, 20, 3, 3, 'F');
    
    doc.setTextColor(194, 65, 12);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('⚠ GENERATED OFFLINE', pageWidth / 2, statusY, { align: 'center' });
    
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.text('Pending sync to server', pageWidth / 2, statusY + 8, { align: 'center' });
  }
}

/**
 * Render dimension pages
 */
function renderDimensionPages(doc, data) {
  const { groupDimensionsForProduction, calculateWallSequences, formatDimensionRow } = require('./FieldPDFLayoutEngine');
  
  let pagesAdded = 0;
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Group dimensions by area
  const areaGroups = groupDimensionsForProduction(data.dimensions);
  
  areaGroups.forEach(areaGroup => {
    doc.addPage();
    pagesAdded++;
    
    let y = 100; // Start below header
    
    // Area title
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`Area: ${areaGroup.area_name}`, 40, y);
    y += 25;
    
    // Wall-to-Wall Dimensions
    if (areaGroup.wall_dimensions.length > 0) {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Wall-to-Wall Dimensions', 40, y);
      y += 20;
      
      // Table header
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text('#', 40, y);
      doc.text('Type', 60, y);
      doc.text('Imperial', 120, y);
      doc.text('Metric', 200, y);
      doc.text('Tolerance', 270, y);
      doc.text('Benchmark', 340, y);
      doc.text('Notes', 420, y);
      
      y += 5;
      doc.setLineWidth(0.5);
      doc.line(40, y, pageWidth - 40, y);
      y += 12;
      
      // Wall sequences
      const sequences = calculateWallSequences(areaGroup.wall_dimensions);
      
      Object.entries(sequences).forEach(([type, dims]) => {
        if (dims.length === 0) return;
        
        dims.forEach((dim, idx) => {
          if (y > 700) {
            doc.addPage();
            pagesAdded++;
            y = 100;
          }
          
          const row = formatDimensionRow(dim, idx);
          
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(8);
          doc.text(row.index.toString(), 40, y);
          doc.text(row.type, 60, y);
          doc.setFont('helvetica', 'bold');
          doc.text(row.imperial, 120, y);
          doc.setFont('helvetica', 'normal');
          doc.text(row.metric, 200, y);
          doc.text(row.tolerance, 270, y);
          doc.text(row.benchmark, 340, y);
          doc.setFontSize(7);
          doc.text(row.notes, 420, y);
          
          y += 15;
        });
        
        y += 5; // Space between types
      });
      
      y += 10;
    }
    
    // Vertical Dimensions
    if (areaGroup.vertical_dimensions.length > 0) {
      if (y > 600) {
        doc.addPage();
        pagesAdded++;
        y = 100;
      }
      
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('Vertical Dimensions', 40, y);
      y += 20;
      
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.text('#', 40, y);
      doc.text('Type', 60, y);
      doc.text('Imperial', 120, y);
      doc.text('Metric', 200, y);
      doc.text('Benchmark', 270, y);
      
      y += 5;
      doc.line(40, y, pageWidth - 40, y);
      y += 12;
      
      areaGroup.vertical_dimensions.forEach((dim, idx) => {
        if (y > 700) {
          doc.addPage();
          pagesAdded++;
          y = 100;
        }
        
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.text((idx + 1).toString(), 40, y);
        doc.text(dim.measurement_type, 60, y);
        doc.setFont('helvetica', 'bold');
        doc.text(dim.display_value_imperial, 120, y);
        doc.setFont('helvetica', 'normal');
        doc.text(dim.display_value_metric, 200, y);
        doc.text(dim.benchmark_label || '-', 270, y);
        
        y += 15;
      });
    }
  });
  
  return pagesAdded;
}

/**
 * Render benchmarks page
 */
function renderBenchmarksPage(doc, data, pageNum) {
  const { enrichBenchmarksWithUsage, formatBenchmarkRow } = require('./FieldPDFLayoutEngine');
  
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 100;
  
  // Page header
  doc.setFillColor(239, 68, 68); // Red background for benchmark section
  doc.rect(0, 80, pageWidth, 35, 'F');
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('BENCHMARK REFERENCE POINTS', 40, y);
  doc.setTextColor(0, 0, 0);
  y += 35;
  
  // Important note box
  doc.setFillColor(254, 243, 199); // Amber background
  doc.rect(40, y, pageWidth - 80, 30, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(146, 64, 14);
  doc.text('IMPORTANT: All vertical measurements (BM-C, BM-F, F-C) reference these benchmarks.', 50, y + 12);
  doc.text('Verify benchmark elevations before production.', 50, y + 22);
  doc.setTextColor(0, 0, 0);
  y += 40;
  
  // Enrich with usage data
  const enrichedBenchmarks = enrichBenchmarksWithUsage(data.benchmarks, data.dimensions);
  
  // Table header
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('●', 40, y);
  doc.text('Label', 55, y);
  doc.text('Type', 120, y);
  doc.text('Elevation', 180, y);
  doc.text('Area', 250, y);
  doc.text('Used By', 320, y);
  doc.text('Established', 380, y);
  doc.text('Date', 480, y);
  
  y += 5;
  doc.setLineWidth(1);
  doc.line(40, y, pageWidth - 40, y);
  y += 12;
  
  // Benchmark rows with color coding
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  
  enrichedBenchmarks.forEach((bm, idx) => {
    if (y > 700) {
      doc.addPage();
      y = 100;
    }
    
    const row = formatBenchmarkRow(bm, idx);
    
    // Zebra striping
    if (idx % 2 === 0) {
      doc.setFillColor(248, 250, 252);
      doc.rect(35, y - 8, pageWidth - 70, 16, 'F');
    }
    
    // Color indicator
    const rgb = hexToRgb(bm.color_code);
    doc.setFillColor(rgb.r, rgb.g, rgb.b);
    doc.circle(43, y - 2, 3, 'F');
    
    // Row data
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text(row.label, 55, y);
    
    doc.setFont('helvetica', 'normal');
    doc.text(row.type, 120, y);
    
    doc.setFont('helvetica', 'bold');
    doc.text(row.elevation, 180, y);
    
    doc.setFont('helvetica', 'normal');
    doc.text(row.area, 250, y);
    
    // Reference count
    if (row.reference_count > 0) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(34, 197, 94);
      doc.text(`${row.reference_count} dims`, 320, y);
      doc.setTextColor(0, 0, 0);
    } else {
      doc.setTextColor(150, 150, 150);
      doc.text('Unused', 320, y);
      doc.setTextColor(0, 0, 0);
    }
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.text(row.established_by, 380, y);
    doc.setFontSize(8);
    doc.text(row.date, 480, y);
    
    y += 18;
  });
}

/**
 * Convert hex to RGB
 */
function hexToRgb(hex) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? {
    r: parseInt(result[1], 16),
    g: parseInt(result[2], 16),
    b: parseInt(result[3], 16)
  } : { r: 0, g: 0, b: 0 };
}

/**
 * Render legend page
 */
function renderLegendPage(doc, data, pageNum) {
  const { generateLegendFromData, generateProductionNotes } = require('./FieldPDFLegendGenerator');
  
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 80;
  
  // Page title
  doc.setFillColor(99, 102, 241); // Indigo background
  doc.rect(0, 60, pageWidth, 40, 'F');
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('LEGEND & PRODUCTION GUIDE', pageWidth / 2, y + 10, { align: 'center' });
  doc.setTextColor(0, 0, 0);
  y += 40;
  
  // Generate legend
  const legend = generateLegendFromData(data.dimensions, data.benchmarks);
  
  // Measurement Types Section
  y += 20;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Measurement Types', 40, y);
  y += 18;
  
  legend.measurement_types.forEach(type => {
    if (y > 650) {
      doc.addPage();
      y = 100;
    }
    
    // Color indicator
    const rgb = hexToRgb(type.color);
    doc.setFillColor(rgb.r, rgb.g, rgb.b);
    doc.roundedRect(40, y - 8, 4, 12, 1, 1, 'F');
    
    // Type code and name
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text(type.code, 50, y);
    
    doc.setFont('helvetica', 'normal');
    doc.text(type.name, 100, y);
    
    // Description
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    doc.text(type.description, 100, y + 8);
    
    doc.setTextColor(0, 0, 0);
    y += 20;
  });
  
  // Benchmark Colors Section
  if (legend.benchmarks.length > 0) {
    y += 10;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Benchmark Color Codes', 40, y);
    y += 18;
    
    legend.benchmarks.forEach(bm => {
      if (y > 700) {
        doc.addPage();
        y = 100;
      }
      
      // Color dot
      const rgb = hexToRgb(bm.color_code);
      doc.setFillColor(rgb.r, rgb.g, rgb.b);
      doc.circle(43, y - 2, 4, 'F');
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text(bm.label, 55, y);
      
      doc.setFont('helvetica', 'normal');
      doc.text(`${bm.type} - ${bm.elevation}`, 120, y);
      doc.setFontSize(7);
      doc.setTextColor(100, 100, 100);
      doc.text(`(${bm.area})`, 220, y);
      doc.setTextColor(0, 0, 0);
      
      y += 15;
    });
  }
  
  // Unit Systems
  if (y > 600) {
    doc.addPage();
    y = 100;
  }
  
  y += 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Measurement Units', 40, y);
  y += 18;
  
  legend.unit_systems.forEach(system => {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text(`${system.system}:`, 50, y);
    
    doc.setFont('helvetica', 'normal');
    doc.text(system.format, 120, y);
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    doc.text(`Example: ${system.example}`, 220, y);
    doc.setTextColor(0, 0, 0);
    
    y += 15;
  });
  
  // Production Notes
  if (y > 400) {
    doc.addPage();
    y = 100;
  }
  
  y += 15;
  doc.setFillColor(254, 243, 199);
  doc.rect(40, y - 10, pageWidth - 80, 25, 'F');
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('IMPORTANT PRODUCTION NOTES', 50, y + 5);
  y += 30;
  
  const notes = generateProductionNotes();
  
  notes.forEach(section => {
    if (y > 650) {
      doc.addPage();
      y = 100;
    }
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(section.title, 50, y);
    y += 15;
    
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    
    section.points.forEach(point => {
      const lines = doc.splitTextToSize(`• ${point}`, pageWidth - 110);
      lines.forEach(line => {
        if (y > 720) {
          doc.addPage();
          y = 100;
        }
        doc.text(line, 60, y);
        y += 11;
      });
    });
    
    y += 8;
  });
}

/**
 * Add headers and footers to all pages
 */
function addHeadersAndFooters(doc, data) {
  const pageCount = doc.internal.pages.length - 1;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  for (let i = 2; i <= pageCount; i++) { // Skip cover page
    doc.setPage(i);
    
    // Header
    doc.setFillColor(240, 240, 240);
    doc.rect(0, 0, pageWidth, 50, 'F');
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('MCI FIELD', 40, 30);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(data.metadata.document_id, pageWidth - 40, 30, { align: 'right' });
    
    // Footer
    doc.setFontSize(8);
    doc.text(`Page ${i - 1} of ${pageCount - 1}`, pageWidth / 2, pageHeight - 20, { align: 'center' });
    doc.text(`Rev ${data.metadata.revision_number}`, pageWidth - 40, pageHeight - 20, { align: 'right' });
  }
}