/**
 * Field PDF Generator
 * 
 * Generates production-grade PDFs with jsPDF
 */

import jsPDF from 'jspdf';

/**
 * Generate PDF from normalized dataset
 */
export async function generateFieldPDF(normalizedData, options = {}) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'letter'
  });
  
  let currentPage = 1;
  
  // Page 1: Cover + Metadata
  renderCoverPage(doc, normalizedData);
  
  // Page 2+: Dimensions by area
  const dimensionPages = renderDimensionPages(doc, normalizedData);
  currentPage += dimensionPages;
  
  // Benchmarks page (if any)
  if (normalizedData.benchmarks.length > 0) {
    doc.addPage();
    currentPage++;
    renderBenchmarksPage(doc, normalizedData, currentPage);
  }
  
  // Update metadata with page count
  normalizedData.metadata.page_count = doc.internal.pages.length - 1; // -1 for blank first page
  
  // Add page numbers and headers to all pages
  addHeadersAndFooters(doc, normalizedData);
  
  return {
    pdf: doc,
    blob: doc.output('blob'),
    data_url: doc.output('dataurlstring'),
    metadata: normalizedData.metadata
  };
}

/**
 * Render cover page
 */
function renderCoverPage(doc, data) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Company header
  doc.setFillColor(30, 58, 138); // MCI Blue
  doc.rect(0, 0, pageWidth, 60, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('MCI FIELD', pageWidth / 2, 35, { align: 'center' });
  
  // Document title
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.text('Field Dimension Report', pageWidth / 2, 100, { align: 'center' });
  
  // Project info box
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const boxY = 140;
  const lineHeight = 20;
  
  doc.text('Project:', 60, boxY);
  doc.setFont('helvetica', 'bold');
  doc.text(data.job.name, 140, boxY);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Address:', 60, boxY + lineHeight);
  doc.setFont('helvetica', 'bold');
  doc.text(data.job.address, 140, boxY + lineHeight);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Customer:', 60, boxY + lineHeight * 2);
  doc.setFont('helvetica', 'bold');
  doc.text(data.job.customer_name, 140, boxY + lineHeight * 2);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Area:', 60, boxY + lineHeight * 3);
  doc.setFont('helvetica', 'bold');
  doc.text(data.dimension_set.area, 140, boxY + lineHeight * 3);
  
  // Metadata
  doc.setFont('helvetica', 'normal');
  doc.text('Document ID:', 60, boxY + lineHeight * 5);
  doc.setFont('helvetica', 'bold');
  doc.text(data.metadata.document_id, 140, boxY + lineHeight * 5);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Revision:', 60, boxY + lineHeight * 6);
  doc.setFont('helvetica', 'bold');
  doc.text(`Rev ${data.metadata.revision_number}`, 140, boxY + lineHeight * 6);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Generated:', 60, boxY + lineHeight * 7);
  doc.setFont('helvetica', 'bold');
  doc.text(data.metadata.generated_at, 140, boxY + lineHeight * 7);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Generated By:', 60, boxY + lineHeight * 8);
  doc.setFont('helvetica', 'bold');
  doc.text(data.metadata.generated_by, 140, boxY + lineHeight * 8);
  
  // Status badge
  const statusY = boxY + lineHeight * 10;
  doc.setFillColor(34, 197, 94); // Green
  doc.roundedRect(60, statusY - 10, 100, 20, 3, 3, 'F');
  doc.setTextColor(255, 255, 255);
  doc.text(data.dimension_set.workflow_state.toUpperCase(), 110, statusY + 2, { align: 'center' });
  
  // Offline indicator
  if (data.metadata.offline_generated) {
    doc.setTextColor(255, 140, 0);
    doc.setFontSize(8);
    doc.text('Generated Offline', pageWidth / 2, pageHeight - 20, { align: 'center' });
  }
}

/**
 * Render dimension pages
 */
function renderDimensionPages(doc, data) {
  let pagesAdded = 0;
  
  // Group dimensions by area
  const byArea = {};
  data.dimensions.forEach(dim => {
    if (!byArea[dim.area]) byArea[dim.area] = [];
    byArea[dim.area].push(dim);
  });
  
  Object.entries(byArea).forEach(([area, dims]) => {
    doc.addPage();
    pagesAdded++;
    
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 100; // Start below header
    
    // Area title
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`Area: ${area}`, 40, y);
    y += 30;
    
    // Table header
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('Type', 40, y);
    doc.text('Value', 120, y);
    doc.text('Measured By', 220, y);
    doc.text('Date', 340, y);
    doc.text('Status', 460, y);
    
    y += 5;
    doc.setLineWidth(0.5);
    doc.line(40, y, pageWidth - 40, y);
    y += 15;
    
    // Dimension rows
    doc.setFont('helvetica', 'normal');
    dims.forEach(dim => {
      if (y > 700) { // New page if needed
        doc.addPage();
        pagesAdded++;
        y = 100;
      }
      
      doc.text(dim.measurement_type, 40, y);
      doc.text(dim.display_value, 120, y);
      doc.text(dim.measured_by, 220, y);
      doc.text(dim.measurement_date, 340, y);
      doc.text(dim.status, 460, y);
      
      y += 20;
    });
  });
  
  return pagesAdded;
}

/**
 * Render benchmarks page
 */
function renderBenchmarksPage(doc, data, pageNum) {
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 100;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Benchmarks', 40, y);
  y += 30;
  
  // Table header
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Label', 40, y);
  doc.text('Type', 120, y);
  doc.text('Elevation', 200, y);
  doc.text('Area', 280, y);
  doc.text('Established By', 360, y);
  
  y += 5;
  doc.setLineWidth(0.5);
  doc.line(40, y, pageWidth - 40, y);
  y += 15;
  
  // Benchmark rows
  doc.setFont('helvetica', 'normal');
  data.benchmarks.forEach(bm => {
    doc.text(bm.label, 40, y);
    doc.text(bm.type, 120, y);
    doc.text(`${bm.elevation} ${bm.elevation_unit}`, 200, y);
    doc.text(bm.area, 280, y);
    doc.text(bm.established_by, 360, y);
    
    y += 20;
  });
}

/**
 * Add headers and footers to all pages
 */
function addHeadersAndFooters(doc, data) {
  const pageCount = doc.internal.pages.length - 1;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  for (let i = 2; i <= pageCount; i++) { // Skip cover page
    doc.setPage(i);
    
    // Header
    doc.setFillColor(240, 240, 240);
    doc.rect(0, 0, pageWidth, 50, 'F');
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('MCI FIELD', 40, 30);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(data.metadata.document_id, pageWidth - 40, 30, { align: 'right' });
    
    // Footer
    doc.setFontSize(8);
    doc.text(`Page ${i - 1} of ${pageCount - 1}`, pageWidth / 2, pageHeight - 20, { align: 'center' });
    doc.text(`Rev ${data.metadata.revision_number}`, pageWidth - 40, pageHeight - 20, { align: 'right' });
  }
}